### ISSUE TITLE
With full-screen width on typical laptop screen size, the header wraps

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#258]
Perhaps moving the "Center for Open Science" a bit to the left will fix.

![screen shot 2014-12-22 at 5 46 06 pm](https://cloud.githubusercontent.com/assets/1761504/5532237/91c05ae0-8a02-11e4-85e6-5f3bdd87a6eb.png)

**Comment by erinspace** [comment]
Made a change to the way this works, perhaps there is a better solution but closing this particular issue!
