### ISSUE TITLE
Add sponsors and sponsor information

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/cos.io#271]
Rackspace - Monthly credit for cloud services, http://www.rackspace.com/

![rackspace logo_no 1 mgd_no tag_color-2](https://cloud.githubusercontent.com/assets/512000/5665291/61ea4ea4-9725-11e4-8ab2-8cae46ba9255.png)

Spanning -Non-profit discount on "Backup For Google Apps", http://spanning.com/

We meed more information under Ready Force and Zipfian.

 @AndrewSallans can add more details on those.

**Comment by saradbowman** [comment]
Readyforce got bought out by LookSharp and has asked that we change their logo/link - but they didn't get bought out until the end of 2014. @AndrewSallans and I are concerned about interrupting the space/time continuum by changing this entry for 2014, but going forward, if they continue to offer in kind donations, we should change the logo.

**Comment by erinspace** [comment]
Oh this also raises the question, do we add a new 2015 tab?

**Comment by AndrewSallans** [comment]
We also need to add a 2015 line for MailChimp with a 15% non-profit discount.

For ReadyForce:  "Non-profit use of recruitment services for developer internships."

For Zipfian:  "Non-profit use of recruitment services for developers and statistical consultants."

Yes, @erinspace , please add the tab for 2015 and work it up as a draft.  I can check it over with numbers for 2015 as you are able to frame it out.  Thanks!

**Comment by AndrewSallans** [comment]
Another to add for 2014/2015 is Buffer (bufferapp.com).  Also, for consistency, let's not do percentages on the site.

So, updates:

MailChimp:  "Discount for email list subscription services."  2015 only

Buffer:  "Discount for social media scheduling services."  2014/2015

ReadyForce:  "Use of recruitment services for developer internships."  2014

Zipfian:  "use of recruitment services for developers and statistical consultants."  2014

Thanks!
Andrew
