### ISSUE TITLE
Add Prometheus Research to Partners page, and grant info to grants page

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#277]
@AndrewSallans can provide the details for a blurb about the partnership and the amount of funding for the grant (actually from NIH not Prometheus).

http://www.prometheusresearch.com/

**Comment by AndrewSallans** [comment]
For the partnership page:  
Prometheus Research (link: http://www.prometheusresearch.com/)
"Prometheus Research has partnered with COS on use of the OSF and its application programming interface (API), to connect with their open source, integrated Research Exchange Database (RexDB, link: http://www.rexdb.org/) to create a library of Electronic Data Capture (EDC) instruments.  This will enable OSF users to easily utilize EDC instruments within their OSF projects."
Use Prometheus Research logo:  http://www.prometheusresearch.com/

For the funding page:  
National Institute of Mental Health (part of the National Institutes of Health) (link: http://www.nimh.nih.gov/index.shtml)
$29,341 (on the 2015 tab).  
"Subcontract from Prometheus Research for integration of the OSF and the Research Exchange Database (RexDB, link: http://www.rexdb.org/) to create a library of Electronic Data Capture (EDC) instruments.".
@bnosek do you think it would be better to go with the NIH logo or the Prometheus logo, or both?  I would say NIH in this case.

**Comment by JeffSpies** [comment]
NIH.

**Comment by bnosek** [comment]
Agree

**Comment by erinspace** [comment]
initial draft is up here:  https://github.com/erinspace/centerforopenscience.org/tree/sponsors

**Comment by bnosek** [comment]
This was added on production, but the image link is broken:

http://centerforopenscience.org/about_partners/

**Comment by erinspace** [comment]
Logo fixed, thanks for the catch! Closing this issue now because there's now a separate issue for adding 2015 Funders at #317
