### ISSUE TITLE
Team page updates

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#284]
Fabian is now "Developer" rather than "Developer Intern".
Sam is now "Developer" rather than "Developer Intern".
Harry can be moved out of Alumni into team list and is also "Developer"

Sam and Harry have not started yet, but probably will have by the time this issue is addressed.

**Comment by AndrewSallans** [comment]
Yes timing is close enough to go ahead on this with Sam and Harry when
ready.
