### ISSUE TITLE
Problem with menu

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/cos.io#290]
centerforopenscience.org/osf seems to have an issue showing the menu:  
![screen shot 2015-01-29 at 2 24 05 pm](https://cloud.githubusercontent.com/assets/2151933/5964509/a298e458-a7c2-11e4-857a-491a2c090f22.png)

**Comment by saradbowman** [comment]
fixed thanks to @jlcohoon 

@erinspace can you close this one out? Thanks!

**Comment by erinspace** [comment]
Yep!
