### ISSUE TITLE
Links to section in tab widget don't work in Firefox

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/cos.io#295]
**Summary**: When visiting a page with a tabbed navigation widget, links do not open the desired tab in Firefox. They do work in Chrome: this appears to be a cross-browser issue.

**Example link/ testcase**: http://centerforopenscience.org/involved_participate/#tab_4

**Observed result**: In Firefox 35, the link given above loads with no tabbed section selected. The content area at the right side of the page is a white rectangle. Once the section label ("developers") is clicked, the section will appear in the content area. (see screenshot below)

![ticket](https://cloud.githubusercontent.com/assets/2957073/6182283/f965a42c-b30e-11e4-9cb3-fcef48bf79eb.png)

**System details**: Link does not work with Firefox 35.0.1 on Mac OS 10.10.1. Link does work as expected in Google Chrome 40.0.2214.111 on same machine.

**Additional notes**: After clicking on a link, the browser address bar does not correctly update to show the open section. It continues to show whatever URL the page was loaded as. (making it slightly harder for a visitor to get a link to the content). Eg if the user visits the page with the link above and then clicks "Scientists", the address bar will still show a link to #tab_4. This happens in both Chrome and Firefox.

**Comment by JeffSpies** [comment]
@caneruguz, do you mind taking a look at this?

**Comment by caneruguz** [comment]
This was due to a very common error developers (uh... like me) make when working with complex jquery selectors that use variables so the closing of the selector is difficult to see.  In this case a "]" was missing from the end. 

Chrome ignores this error in its rendering so if you are developing with Chrome you will not catch errors like this that Chrome tolerates. 

Fix is in the PR linked.

**Comment by abought** [comment]
Confirmed that PR fixes the basic tab view per screenshot above. Works for me in Firefox and Chrome.

The secondary issue (additional notes) still remains- address bar doesn't update to reflect the opened section, which makes it trickier to send someone a link to that part of the site. That could be separated out as a minor issue.

**Comment by caneruguz** [comment]
The secondary issue is another bug though, I recommend you create a new issue for this. There is not a very elegant fix but I have a solution; it works in chrome, firefox and safari, I'm testing with IE now, I will send a new PR, but these two things are related but should be able to be applied separately.

**Comment by caneruguz** [comment]
@Jeff any ideas about this code? I didn't want to include any history writing and rather use location since it's only an anchor and should not actually reload the page (and this seems more cross-browser safe): 

```javascript 
    $('a[data-toggle="tab"]').click(function(){
        var tabNumber = $(this).attr('href').slice(5,6),
            base,
            newurl;
        if (tabNumber) {
            base = location.href.split('#');
            newurl = base[0] + '#tab_' + tabNumber;
            window.location.assign(newurl);
        }
    });
```
