### ISSUE TITLE
Opening section of tab widget doesn't update address bar

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/cos.io#298]
Split from #295 as separate issue:

When clicking a section on a tabbed widget ([example](http://centerforopenscience.org/involved_participate/#tab_4)), the address bar does not reflect to open the currently opened section. Instead, it shows whatever URL was originally used to access the page.

Eg if the user visits the page with the link above and then clicks "Scientists", the address bar will still show a link to #tab_4. 

This is a minor usability quirk: it makes it more difficult for users to get and share links to a specific part of the site.

Occurs in Firefox 35 and Chrome 40, Mac OS 10.10.

**Comment by caneruguz** [comment]
This is the suggested solution. I didn't want to include any history writing and rather use location since it's only an anchor and should not actually reload the page (and this seems more cross-browser safe): 

``` javascript
    $('a[data-toggle="tab"]').click(function(){
        var tabNumber = $(this).attr('href').slice(5,6),
            base,
            newurl;
        if (tabNumber) {
            base = location.href.split('#');
            newurl = base[0] + '#tab_' + tabNumber;
            window.location.assign(newurl);
        }
    });
```

**Comment by caneruguz** [comment]
Thanks @abought, I appreciate the detailed reporting, we should get this resolved very soon.

**Comment by abought** [comment]
As a note, this issue was originally written regarding `involved_participate.mako`, but   `communities.mako` is also affected.
