### ISSUE TITLE
Add TESS to the partners page

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#315]
http://www.tessexperiments.org/

Time-sharing Experiments for the Social Sciences (TESS) is an NSF-funded project that supports free data collections on representative samples of U.S. adults for experimental research.  COS and TESS have partnered to host TESS's entire historical and future data catalog of more than 300 experiments on the Open Science Framework.

**Comment by saradbowman** [comment]
@erinspace can you close this one out? Thanks!

**Comment by erinspace** [comment]
Yep!
