### ISSUE TITLE
Add 2015 funders to funders page

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#317]
I think that this was drafted but is not in production yet.

http://centerforopenscience.org/about_sponsors/

To it, we should add Hewlett Foundation for $100K Africa project.

**Comment by AndrewSallans** [comment]
@erinspace are you working on this one still?  If so, perhaps we could take a look at a draft version today or tomorrow and then get it out there soon?  If not, please let me know so that we can do it another way.

**Comment by erinspace** [comment]
@AndrewSallans yep, ready for review whenever you like
