### ISSUE TITLE
Add OKF to partners page

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#336]
http://centerforopenscience.org/about_partners/

@AndrewSallans probably has text from the press release and/or grant to describe the partnership.

**Comment by AndrewSallans** [comment]
I sent a blurb to okf yesterday; waiting for feedback and then will post.

**Comment by AndrewSallans** [comment]
Organization:  Open Knowledge

Blurb:  Open Knowledge has partnered with COS on the development of Open Trials, an online database of the world's clinical research trials.  This project will utilize the Open Science Framework infrastructure to advance transparency and public access to clinical research trials information.

@saradbowman can you add this?  Perhaps this logo (http://blog.okfn.org/files/2014/11/OpenKnowledge_LOGO_COLOUR_CMYK-e1416917169844.jpg)?

**Comment by saradbowman** [comment]
done!
