### ISSUE TITLE
Add Billy and Jolene to Our Team page

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/cos.io#337]
Billy is an accomplished photographer - maybe he'd be willing to take up that task for the individual and team shots.

**Comment by AndrewSallans** [comment]
Yes, already in discussion on this.

**Comment by saradbowman** [comment]
Yep, already taken care of- working on adding staff and partners to the
page as well as top guidelines splash page.   Will be done /PR submitted
tomorrow or Tuesday

**Comment by saradbowman** [comment]
@erinspace can you close this one out? Thanks!

**Comment by erinspace** [comment]
Sure thing!
