### ISSUE TITLE
COS Board Additions

### ISSUE THREAD

**Issue by denisehlmn** [CenterForOpenScience/cos.io#357]
Please add the following bio's and headshots to the COS Board portion of our website. Thank you!

![dsc_0046](https://cloud.githubusercontent.com/assets/7724924/7618990/d6b0cf36-f983-11e4-87ce-f5c0b38d0389.JPG)

Andrew Updegrove

Andrew Updegrove is a co-founder and partner of the Boston law firm of Gesmer Updegrove LLP.  

Since 1988 he has served as legal counsel to over 135 standards development organizations and 

open source foundations, most of which he has helped structure and launch.  He has been 

retained by many of the largest technology companies in the world to assist them in forming such 

He has also written and spoken extensively on the topics of consortia, standard setting and open 

source software, has given testimony to the United States Department of Justice, Federal Trade 

Commission, and Congressional and State legislative committees on the same topics, and has 

filed “friend of the court” briefs on a pro bono basis with the Federal Circuit Court, Supreme Court, 

and Federal Trade Commission in support of standards development in leading standards-related 

litigation.  In 2002, he launched ConsortiumInfo.org, a website intended to be the most detailed 

and comprehensive resource on the Internet on the topics of consortia and standard setting, as 

well as Standards Today, an eJournal of news, ideas and analysis in the standard setting and 

open source areas with over 7,000 subscribers around the world.  In 2005, he launched the 

Standards Blog.  ConsortiumInfo.org serves over 10 million page views annually.

He has been a member of the United States Standards Strategy revision committee, has served 

on a National Academy of Sciences committee on standards-related intellectual property rights 

policies commissioned by the US PTO, and has received the President’s Award for Journalism 

from American National Standards Institute (ANSI).  His current and past Board service includes 

the Boards of Directors of ANSI, the Linux Foundation and the Free Standards Group, and the 

Boards of Advisors of HL7 and Open Source for America.  He is a graduate of Yale University 

and the Cornell University Law School.

![heather photo](https://cloud.githubusercontent.com/assets/7724924/7618996/e2e8f634-f983-11e4-943c-d2aafbd98c4a.jpg)

Heather Joseph

Heather Joseph serves as the Executive Director of SPARC, (the Scholarly Publishing 

and Academic Resources Coalition), an international coalition of academic and research 

libraries working to expand the global, open communication of research and scholarship.

She leads the strategic and operational activities of the organization, and has focused 

SPARC’s efforts on creating and supporting new models for sharing digital articles, data 

and educational resources. Under her stewardship, SPARC has become widely 

recognized as the leading international force for effective Open Access policy advocacy, 

successfully securing legislation and executive actions in the U.S., Canada and Europe. 

To support SPARC’s mission, Ms. Joseph spearheaded the launch of the student Right to 

Research Coalition, an international advocacy organization that has grown to represent 

nearly seven million students worldwide, and provides opportunities for students and 

early career researchers to actively engage in advocacy for the open sharing of research 

and scholarship.  She is also the convener of the Alliance for Taxpayer Access, a national 

coalition of major U.S. education, research and advocacy organizations that advocate for 

public access to the results of federally funded research.  

Prior to joining SPARC, she spent 15 years as a publishing executive in both commercial 

and not-for-profit publishing organizations. Ms. Joseph serves on the Board of Directors 

of a number of non-profit organizations, including the Public Library of Science (PLoS), 

DuraSpace and the Center for Open Science.  She is an active participant in projects and 

committees at several U.S. federal agencies, and was recently appointed to the Secretary 

of Commerce’s advisory Council on Digital Data.  Ms. Joseph is a frequent speaker and 

writer on topics relating to opening up access to knowledge.

**Comment by jlcohoon** [comment]
a pull request is in for this

**Comment by denisehlmn** [comment]
Thank you!

On Wed, May 27, 2015 at 12:37 PM, jlcohoon notifications@github.com wrote:

> a pull request is in for this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CenterForOpenScience/centerforopenscience.org/issues/357#issuecomment-105987312
> .

## 

_Denise Holman_
Office Manager & Events Coordinator
Center for Open Science
210 Ridge McIntire Road, Suite 500
Charlottesville, VA 22903-5803
(804) 432-9522

**Comment by saradbowman** [comment]
@erinspace can you close this one please? Thanks!

**Comment by erinspace** [comment]
yep!
