### ISSUE TITLE
Replace social media logo bar in footer with counter/share bar

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/cos.io#368]
Currently has this:
![screen shot 2015-05-28 at 9 32 57 am](https://cloud.githubusercontent.com/assets/2151933/7861218/d042f09e-051c-11e5-8ec6-58158d1607ee.png)

Recommending that we switch to one like this instead to boost social media follows:
![screen shot 2015-05-28 at 9 35 31 am](https://cloud.githubusercontent.com/assets/2151933/7861243/f23dde5c-051c-11e5-8ce2-c3db4541c524.png)

**Comment by lbanner** [comment]
:+1:

**Comment by GaryKriebel** [comment]
@JeffSpies @bnosek ... same concern as with https://github.com/CenterForOpenScience/osf.io/issues/2860?

**Comment by JeffSpies** [comment]
Discussion is required off-line. Closing for now.
