### ISSUE TITLE
[Production and Staging] Typo in "Getting Started" Forks Explanation

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/cos.io#381]
Go to osf.io and log in
Click on the "help" dropdown menu at the top of the screen and select "Getting started"
Go to the "structure" heading on the left hand side of the screen and click on the subheading "forks"
At the end of the second line in the fourth paragraph the sentence does not make sense (below).

"If you were originally linking to someone else's project but would now like to edit it and make your own version, from the project overview page, find the linked project from the and hit the small fork button."

**Comment by erinspace** [comment]
Hi @WillBanner! I think maybe this issue belongs over on https://github.com/CenterForOpenScience/osf.io/issues, as it's for the OSF (and not for the http://cos.io website).

**Comment by WillBanner** [comment]
This issue was moved to CenterForOpenScience/osf.io#3090
