### ISSUE TITLE
News page: Open Trials is out of alignment

### ISSUE THREAD

**Issue by TimErrington** [CenterForOpenScience/cos.io#397]
If you go to the news page, http://centerforopenscience.org/news/, the alignment of the pieces on Open Trials is mis-aligned. And the Harvard Business Review text seems one line too close to the Pacific Standard text compared to all the rest.

![screen shot 2015-06-24 at 1 36 05 pm](https://cloud.githubusercontent.com/assets/5816601/8336952/feb04e86-1a75-11e5-8f12-0ff321bbd4d7.png)

**Comment by saradbowman** [comment]
What browser are you on @TimErrington? I'm not seeing the issue on Chrome

**Comment by TimErrington** [comment]
Sorry, forgot to add that detail - Safari

**Comment by saradbowman** [comment]
I can't reproduce the error, so I'm not sure what's up. regardless, an update went in last night to add the quarterly newsletter, so I'm curious if you still see the problem?

**Comment by GaryKriebel** [comment]
Yes, if you reduce the size of the screen, you can reproduce the error.
![screen shot 2015-06-25 at 9 14 48 am](https://cloud.githubusercontent.com/assets/9437946/8355022/a5f03aae-1b1a-11e5-9f48-e23672139aaf.png)

Most likely due to the length of the article title.

**Comment by TimErrington** [comment]
Thanks, I just showed this to Sara as well. And it occurs with chrome and safari

**Comment by GaryKriebel** [comment]
Yes, was about to add the same.
![screen shot 2015-06-25 at 9 21 33 am](https://cloud.githubusercontent.com/assets/9437946/8355170/9e9984b2-1b1b-11e5-8826-a20acabefa97.png)

It will correct itself when it goes to one column.
![screen shot 2015-06-25 at 9 22 18 am](https://cloud.githubusercontent.com/assets/9437946/8355189/bdee7b10-1b1b-11e5-8a37-93e803b8cf47.png)
