### ISSUE TITLE
Broken link for example registration

### ISSUE THREAD

**Issue by TomHardwicke** [CenterForOpenScience/cos.io#401]
# STEPS

Go to here: http://centerforopenscience.org/involved_participate/

Click on "See an example registration" which is one of the light blue boxes on the right hand side of the page. Clicking the link takes you to here: https://osf.io/h8sp7/
# EXPECTED

Expected to see an example registration on the osf
# ACTUAL

Recieved this message:

"Forbidden. You do not have permission to perform this action."

**Comment by saradbowman** [comment]
replacing link with a link to many labs registration; nice catch @TomHardwicke !
