### ISSUE TITLE
Update Flowdock logo on Sponsors page

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/cos.io#443]
## Description

Right now, the flowdock logo on the Sponsors page (http://centerforopenscience.org/about_sponsors/) is the old one:

![old_logo](https://cloud.githubusercontent.com/assets/7093086/8968271/0be4dfcc-360a-11e5-9287-7b2ac7415002.png)

Flowdock has updated the logo, so we should update accordingly. On Flowdock's website, they are showing this now:

![new_flowdock_logo](https://cloud.githubusercontent.com/assets/7093086/8968659/a9ce561c-360c-11e5-8b61-5f903086ff5f.png)

**Comment by NatashaRichter** [comment]
Actually, I'm working on this!

**Comment by saradbowman** [comment]
@NatashaRichter do you want me to update the flowdock logo or are you still working on this?

**Comment by saradbowman** [comment]
In my next PR. @erinspace can you close this? thanks!

**Comment by erinspace** [comment]
Yep!
