### ISSUE TITLE
Broken Links on News Page

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/cos.io#487]
I ran a link checker on the news portion of the site.  Here are the results.

http://www.billyhunt.com/cos_news_broken_links.html

There are some about.html links broken on the news page, and some articles whose links have expired.

**Comment by saradbowman** [comment]
Thanks, Billy. I've found the dead links from your results and I'll work
them into my next PR.

**Comment by saradbowman** [comment]
@erinspace fixed this - can you close? Thanks!

**Comment by erinspace** [comment]
Yep!
