### ISSUE TITLE
[cos.io] Photo stream on front page is not loading 

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/cos.io#508]
moved from community repo

Error in Console is The page at 'https://cos.io/' was loaded over HTTPS, but requested an insecure script 'http://api.flickr.com/services/feeds/photos_public.gne?lang=en-us&format=js…=jQuery110206001207181252539_1444661849173&id=99620615@N06&_=1444661849174'. This request has been blocked; the content must be served over HTTPS.

**Comment by saradbowman** [comment]
@erinspace can you help with this (or point to someone who might)? I am at a loss..

**Comment by AndrewSallans** [comment]
@GaryKriebel  resurfacing a need to fix this one.
