### ISSUE TITLE
rename repo to cos.io

### ISSUE THREAD

**Issue by chadwhitacre** [CenterForOpenScience/cos.io#580]
The canonical domain for the website is now cos.io, not centerforopenscience.org. On the pattern of osf.io, I tried accessing this repo by munging the URL on GitHub and hitting:

https://github.com/CenterForOpenScience/cos.io

GitHub now has [good support for renaming](https://help.github.com/articles/renaming-a-repository/), so this would be low risk.

**Comment by abought** [comment]
As a note: there is actually a separate `cos.io` repo now, which is used for development of the new (Django-based) website.

https://github.com/CenterForOpenScience/cos.io

**Comment by chadwhitacre** [comment]
I suppose this can be closed, then! :-)
