### ISSUE TITLE
"COS supports shifting incentives and practices"

### ISSUE THREAD

**Issue by pattisdr** [CenterForOpenScience/cos.io#611]
I was talking with a researcher from VSU recently.  He visited our home page and was confused about the sentence "COS supports <em>shifting</em> incentives and practices".   I attempted to explain about reproducibility concerns and incentives for replication, before I realized it was a part of speech confusion. 

He said, 

> We talked about this yesterday and I agree with both points.  But the phrase ‘supports shifting incentives and practices’ threw me.  I see I was misreading the sentence, but my first thought was ‘what’s a ‘shifting incentive’?’.  The explanation is much clearer to me than the sentence.  It may be me only, but have there been other inquiries as to the meaning of this sentence?

Perhaps rephrasing would be helpful?

**Comment by rustyspeidel** [comment]
i have modified this page substantially this week, have a look once it's live and we can see if what i changed makes it better.

**Comment by pattisdr** [comment]
Closing...old ticket. Language has greatly improved on new cos site.
