### ISSUE TITLE
Dead link on integration grant info. page

### ISSUE THREAD

**Issue by aprilcs** [CenterForOpenScience/cos.io#667]
STEPS

Go to here: https://cos.io/integrationgrants/

Click on "v2 Open Science Framework API" link.

EXPECTED

Expected to see information on the API.

ACTUAL

"Page not found. The requested resource could not be found. If this should not have occurred and the issue persists, please report it to support@osf.io."

**Comment by saradbowman** [comment]
@AndrewSallans should we remove this page entirely?
