### ISSUE TITLE
fix a small typo on https://cos.io/jobs/

### ISSUE THREAD

**Issue by raj-maurya** [CenterForOpenScience/cos.io#793]
Hi,

Got a spell error for "tranparent" instead of "transparent"  on the page https://cos.io/jobs/  [just below the Youtube video]

**Comment by AndrewSallans** [comment]
Thanks for the fix!

**Comment by ulgens** [comment]
The branch has merged but issue is still open. I think it should be closed too :)

**Comment by raj-maurya** [comment]
Thanks @AndrewSallans @ulgens 

Closing issue!
