### ISSUE TITLE
[cos.io] Developers nav and page need resurrecting from the dead

### ISSUE THREAD

**Issue by nkmeyers** [CenterForOpenScience/cos.io#865]
I think there is still no developer's page avail thru the web site nav or the old nav URLS.  

Can we resurrect the page content and redirect the old link that used to go to developers page? We need a way to tell devs and others the links to our github, our readthedocs, our developer jobs and internships etc. 

I think this is the URL we need to change the redirect on - it is going to the ambassadors' page content not the developers' page 
https://cos.io/involved_participate/#tab_5  

interestingly it seems like all the #tabs on https://cos.io/involved_participate/ (the old "Get Involved" Pull-Down items) are going to ambassadors, none to devs or scientists or jobs (the other three old nav options on this pull down that used to sit along w/ambassadors target). 

can we get a nav item and web content back for a developers page? 

This is the content we need to resurface 
https://web.archive.org/web/20160328162805/https://cos.io/involved_participate/#tab_4

as below

![image](https://cloud.githubusercontent.com/assets/3044754/22149455/e9ad8440-dee1-11e6-989a-9d691cfb42c9.png)

**Comment by rustyspeidel** [comment]
we have a JIRA board for these, although this content is all on the new site under Communities

**Comment by nkmeyers** [comment]
cool - thx - I  see there's a nav item for the dev community page in the pull-down now too, next-up a content refresh for this page at : https://cos.io/our-communities/software-developers/ ?

**Comment by nkmeyers** [comment]
Ok to close this ticket now from my pov.
